import type { Metadata } from "next";
import { Shippori_Mincho, Nunito } from "next/font/google";
import "./globals.css";
import Navbar from "./components/navbar/navBar";
import Providers from "./components/auth/AuthProvider";

const shippori = Shippori_Mincho({
  subsets: ["latin"],
  weight: ["400"],
  variable: "--font-shippori",
});

const nun = Nunito({
  subsets: ["latin"],
  variable: "--font-nun",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <Providers>
        <body className={`${shippori.variable} ${nun.variable}`}>
        <script
          crossOrigin="anonymous"
          src="//unpkg.com/react-scan/dist/auto.global.js"
        />
        <Navbar />
          <main className={"pt-16"}>
          {children}
          </main>
        </body>
      </Providers>
    </html>
  );
}
